### PR TITLE
make sure $java_home is set after install

### PR DESCRIPTION
**Pull request by itlackey**
this should fix the issue with setting $env:JAVA_HOME to $null
issue #9

### CODE REVIEW

**Comment by digitaldrummerj** [comment]
the $java_home is already set on line 22

**Comment by itlackey** [comment]
Ahh looking at the get-java-home function now I see it has changed from the version that is published with the choco package. The published one pulls from the registry and that causes the issue because the registry key is not there prior to the install. Shown in the comon.ps1 here: https://chocolatey.org/packages/jdk7/7.0.79

The version published to chocolatey is not setting JAVA_HOME as expected.

**Comment by digitaldrummerj** [comment]
I just realized the same thing as well.  I will be submitting an update shortly

**Comment by itlackey** [comment]
Awesome, thanks!

**Pull request closed without merging**
